return {}
-- return {
--   "olimorris/codecompanion.nvim",
--   dependencies = {
--     "nvim-lua/plenary.nvim",
--     "nvim-treesitter/nvim-treesitter",
--   },
--   opts = {
--     log_level = "DEBUG",
--     adapters = {
--       http = {
--         ollama = function()
--           return require("codecompanion.adapters").extend("ollama", {
--             env = {
--               url = "http://1.208.108.242:37144",
--               api_key = "b003ca6cade39cac388baa1b870ae5aeece97eb7533d4215763f1bf8e5d65b9b",
--             },
--             headers = {
--               ["Content-Type"] = "application/json",
--               ["Authorization"] = "Bearer b003ca6cade39cac388baa1b870ae5aeece97eb7533d4215763f1bf8e5d65b9b",
--             },
--             schema = {
--               model = {
--                 default = "qwen3-coder:latest",
--               },
--             },
--           })
--         end,
--       }
--     },
--     interactions = {
--       chat = {
--         adapter = "ollama",
--         tools = {
--           ["files"] = {
--             enabled = true,
--           },
--           ["editor"] = {
--             enabled = true,
--           },
--         },
--       },
--       inline = { adapter = "ollama" },
--     },
--   },
-- }
